### ISSUE TITLE
Can not use docker image linux/arm64

### ISSUE THREAD

**Issue by zainal-abidin-assegaf** [Pathairush/airflow-hive-spark-sqoop#1]
Can we convert ppatcoding/airflow linux/arm64 to linux/amd64 ??

My machine can not run docker image linux/arm64,

Thank you

**Comment by zainal-abidin-assegaf** [comment]
![image](https://user-images.githubusercontent.com/22811935/117756005-8a70c300-b247-11eb-850d-c89f151d4830.png)

I have recreated your dockerfile in amd64 env , now is working properly, but how to use airflow and sqoop to ETL from postgres to hdfs ??

Thank you

**Comment by Pathairush** [comment]
@4ss3g4f Thanks for the issue. This docker is intended to only run on `linux/arm64`. If you need to run on `linux/amd64`, you can build it yourself, or there are many interesting Airflow with Hadoop components for `linux/amd64` out there in the docker hub.

For how to use airflow and sqoop to ETL from Postgres to HDFS. You can take a look at this [repository](https://github.com/Pathairush/rdbms_to_hdfs_data_pipeline) as a reference. It may not be 100% compatible with what you are looking for (It didn't use the `sqoopOperator` from airflow), but maybe you get some idea.
